config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  resources :receipts
  resources :attractions
  resources :users

  resource :session, only: [:new, :create, :destroy]
  get 'receipts/:id/cheque' => 'receipts#cheque', as: 'cheque'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attraction.rb
class Attraction < ApplicationRecord

  has_many :receipts

end

app/models/receipt.rb
class Receipt < ApplicationRecord

  belongs_to :user
  belongs_to :attraction

  ATTRACTIONS = Attraction.pluck(:name)
  CYCLES = [1, 2]

  def change
    (cash_pay + card_pay) - total_price
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :receipts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def require_signin
    unless current_user
      redirect_to new_session_url, alert: "Пожалуйста, войдите!"
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  before_action :require_signin

  def index
    @receipts = Receipt.includes(:attraction).order(created_at: :desc).limit(20)
  end

end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController

  before_action :require_signin

  layout 'cheque', only: [:cheque]

  def index
    @receipts = Receipt.includes(:attraction)
      .where(created_at: Date.today.beginning_of_day..Date.today.end_of_day)
      .order(created_at: :desc)
  end

  def show
    @receipt = Receipt.find(params[:id])
  end

  def new
    @receipt = Receipt.new
  end

  def create
    @receipt = Receipt.new(receipt_params)
    @receipt.user_id = 1

    if @receipt.cycle == 2 && @receipt.attraction.name == 'Машина'
      @receipt.total_price = @receipt.quantity * 800
    end

    if @receipt.cycle == 2 && @receipt.attraction.name == 'Батут'
      @receipt.total_price = @receipt.quantity * 450
    end

    if @receipt.cycle == 1
      @receipt.total_price = @receipt.quantity * @receipt.attraction.price
    end

    @receipt.save

    redirect_to(root_url, notice: "Успешно. Сдача клиенту: #{@receipt.change}")
  end

  def cheque
    @receipt = Receipt.find(params[:id])

    if @receipt.cycle == 2 && @receipt.attraction.name == 'Машина'
      @cheque_qty = 2
    end

    if @receipt.cycle == 2 && @receipt.attraction.name == 'Батут'
      @cheque_qty = 3
    end

    if @receipt.cycle == 1
      @cheque_qty = 1
    end
  end

  private

  def receipt_params
    params.require(:receipt).permit(
      :client_phone,
      :attraction_id,
      :quantity,
      :cash_pay,
      :card_pay,
      :cycle
    )
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to(root_url, notice: "Добро пожаловать #{user.name}!")
    else
      flash.now[:alert] = 'Неправильный логин/пароль!'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_url, status: :see_other,
      notice: "Вы вышли из аккаунта"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="w-full h-8 bg-green-600 text-white mb-6 font-bold  flex justify-center items-center rounded">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="w-full h-8 bg-red-600 text-white mb-6 font-bold  flex justify-center items-center rounded">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zatt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container mx-auto mt-20 px-5 flex flex-col justify-start">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/cheque.html.erb
<%= yield %>

app/views/main/index.html.erb
<%= render('shared/header') %>

<section>
  <div class="flex flex-row justify-between">
    <h2 class="text-xl font-bold mb-4">Последние чеки</h2>
    <%= link_to('Создать', new_receipt_path, class: 'bg-blue-600 hover:bg-blue-800 text-white font-bold py-2 px-4 rounded mb-4') %>
  </div>

  <table class="min-w-full bg-white border border-gray-300">
    <thead>
      <tr>
        <th class="px-6 py-3 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">ID</th>
        <th class="px-6 py-3 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">Телефон</th>
        <th class="px-6 py-3 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">Аттракцион</th>
        <th class="px-6 py-3 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">Количество</th>
        <th class="px-6 py-3 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">Сумма</th>
        <th class="px-6 py-3 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">Действия</th>
      </tr>
    </thead>
    <tbody class="bg-white divide-y divide-gray-300">
      <% @receipts.each do |receipt| %>
        <tr class="<%= cycle('bg-gray-50', 'bg-white') %>">
          <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500"><%= receipt.id %></td>
          <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500 font-bold">
            <%= link_to(receipt.client_phone, receipt, class: 'text-blue-500 font-bold underline') %>
          </td>
          <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500"><%= receipt.attraction.name %></td>
          <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500"><%= receipt.quantity %></td>
          <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500"><%= receipt.total_price %></td>
          <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
            <%= link_to('Показать чек', cheque_path(receipt), target: '_blank', class: 'text-blue-500 font-bold underline') %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="flex flex-col my-4">
    <%= link_to('Посмотреть все чеки', receipts_path, class: 'underline text-blue-600 text-bold') %>
  </div>
</section>

app/views/receipts/cheque.html.erb
<style>
  .cheque {
    max-width: 266px;
    border: 1px solid grey;
    padding: 16px;
    margin-bottom: 16px;
    font-size: 16px;
  }

  .business {
    font-weight: bold;
    font-size: 18px;
    padding-bottom: 10px;
    margin-bottom: 10px;
    text-align: center;
  }

  .item {
    margin-bottom: 10px;
    padding-bottom: 6px;
    border-bottom: 1px dashed grey;
  }

  .thanks {
    margin: 16px 0;
    text-align: center;
  }
</style>

<% @cheque_qty.times do %>
  <div class="cheque">
    <div class="business">
      <%= @receipt.user.business %>
    </div>

    <div class="item">Клиент: <strong><%= @receipt.client_phone %></strong></div>
    <div class="item">Дата/время: <strong><%= @receipt.created_at.strftime('%d.%m.%Y %H:%M') %></strong></div>
    <div class="item">Аттракцион: <strong><%= @receipt.attraction.name %></strong></div>
    <div class="item">Цикл: <strong><%= @receipt.attraction.cycle_in_minutes %> мин.</strong></div>
    <div class="item">Кол-во персон: <strong><%= @receipt.quantity %></strong></div>
    <div class="item">Сумма: <strong><%= @receipt.total_price %></strong></div>

    <div class="thanks">
      Спасибо за покупку! Желаем вам весело провести время с нами!
    </div>
  </div>
<% end %>

app/views/receipts/index.html.erb
<%= render('shared/header') %>

<section>
  <div class="flex flex-row justify-between align-center">
    <h2 class="text-xl font-bold mb-4">Все чеки за <%= Time.now.strftime('%d.%m.%Y') %></h2>
  </div>

  <table class="min-w-full bg-white border border-gray-300">
    <thead>
      <tr>
        <th class="px-6 py-3 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">ID</th>
        <th class="px-6 py-3 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">Телефон</th>
        <th class="px-6 py-3 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">Аттракцион</th>
        <th class="px-6 py-3 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">Количество</th>
        <th class="px-6 py-3 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">Сумма</th>
        <th class="px-6 py-3 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">Действия</th>
      </tr>
    </thead>
    <tbody class="bg-white divide-y divide-gray-300">
      <% @receipts.each do |receipt| %>
        <tr class="<%= cycle('bg-gray-50', 'bg-white') %>">
          <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500"><%= receipt.id %></td>
          <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500 font-bold"><%= receipt.client_phone %></td>
          <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500"><%= receipt.attraction.name %></td>
          <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500"><%= receipt.quantity %></td>
          <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500"><%= receipt.total_price %></td>
          <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
            <%= link_to('Открыть', receipt, class: 'text-blue-500 font-bold underline') %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/receipts/new.html.erb
<%= render('shared/header') %>

<div class="max-w-2xl">
  <h2 class="font-bold text-xl mb-4 border-bottom-2">Создание чека</h2>
</div>

<div class="max-w-2xl">
  <%= form_with(model: @receipt, class: "w-full") do |form| %>
    <div class="mb-4">
      <%= form.label :client_phone, 'Телефон', class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.text_field :client_phone, autofocus: true, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="mb-4">
      <%= form.label :attraction_id, 'Аттракцион', class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.collection_select :attraction_id, Attraction.all, :id, :name, { prompt: 'Выберите аттракцион' }, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="mb-4">
      <%= form.label :quantity, 'Количество', class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.number_field :quantity, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="mb-4">
      <%= form.label :cycle, 'Время', class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.select :cycle, Receipt::CYCLES, { prompt: 'Выберите время (цикл)' }, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
    </div>

    <div class="mb-4">
      <%= form.label :cash_pay, 'Оплата наличными', class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.number_field :cash_pay, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="mb-4">
      <%= form.label :card_pay, 'Оплата Kaspi', class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.number_field :card_pay, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="flex items-center justify-end">
      <%= form.submit "Создать и распечатать", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 cursor-pointer rounded focus:outline-none focus:shadow-outline" %>
    </div>
  <% end %>
</div>

app/views/receipts/show.html.erb
<%= render('shared/header') %>

<div class="max-w-2xl">
  <h2 class="font-bold text-xl mb-4 border-bottom-2">
    Информация о чеке: №<%= @receipt.id %>
  </h2>
  <div class="pb-4">
    <%= link_to('Показать чек', cheque_path(@receipt), target: '_blank', class: 'text-blue-500 font-bold underline') %>
  </div>
</div>

<div class="max-w-sm">
  <table class="min-w-full bg-white border border-gray-300">
    <tr>
      <th class="py-2 px-4 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">
        Номер чека
      </th>
      <td class="py-2 px-4 text-sm leading-5 text-gray-500">
        <%= @receipt.id %>
      </td>
    </tr>

    <tr>
      <th class="py-2 px-4 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">
        Бизнес
      </th>
      <td class="py-2 px-4 text-sm leading-5 text-gray-500">
        <%= @receipt.user.business %>
      </td>
    </tr>

    <tr>
      <th class="py-2 px-4 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">
        Телефон клиента
      </th>
      <td class="py-2 px-4 text-sm leading-5 text-gray-500">
        <%= @receipt.client_phone %>
      </td>
    </tr>

    <tr>
      <th class="py-2 px-4 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">
        Выбранный аттракцион
      </th>
      <td class="py-2 px-4 text-sm leading-5 text-gray-500">
        <%= @receipt.attraction.name %>
      </td>
    </tr>

    <tr>
      <th class="py-2 px-4 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">
        Цена за единицу (1)
      </th>
      <td class="py-2 px-4 text-sm leading-5 text-gray-500">
        <%= @receipt.attraction.price %>
      </td>
    </tr>

    <tr>
      <th class="py-2 px-4 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">
        Количество персон
      </th>
      <td class="py-2 px-4 text-sm leading-5 text-gray-500">
        <%= @receipt.quantity %>
      </td>
    </tr>

    <tr>
      <th class="py-2 px-4 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">
        Сумма
      </th>
      <td class="py-2 px-4 text-sm leading-5 text-gray-500">
        <%= @receipt.total_price %>
      </td>
    </tr>

    <tr>
      <th class="py-2 px-4 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">
        Оплата наличными
      </th>
      <td class="py-2 px-4 text-sm leading-5 text-gray-500">
        <%= @receipt.cash_pay %>
      </td>
    </tr>

    <tr>
      <th class="py-2 px-4 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">
        Оплата Kaspi
      </th>
      <td class="py-2 px-4 text-sm leading-5 text-gray-500">
        <%= @receipt.card_pay %>
      </td>
    </tr>

    <tr>
      <th class="py-2 px-4 bg-gray-100 text-left text-xs leading-4 font-medium text-gray-600 uppercase tracking-wider">
        Дата / время
      </th>
      <td class="py-2 px-4 text-sm leading-5 text-gray-500">
        <%= @receipt.created_at.strftime('%d.%m.%Y %H:%M') %>
      </td>
    </tr>

  </table>
</div>

app/views/shared/_header.html.erb
<header>
  <div class="mb-10 flex flex-row justify-between content-center align-center items-center">
    <h1 class="text-3xl font-bold">
      🏠 <%= link_to('ИП Ибрагимжанов', root_path, class: 'text-blue-500 font-bold hover:underline') %>
    </h1>
    <% if current_user %>
      <div class="flex flex-row justify-end content-center align-center items-center">
        <p class="font-bold mr-2"><%= current_user.name %></p>
        <%= link_to('Выйти 👉', session_path,
          data: { turbo_method: :delete },
          class: 'bold text-blue-600 bg-transparent rounded border-2 border-rounded border-blue-600 text-center px-2 py-1 hover:bg-blue-600 hover:text-white') %>
      </div>
    <% end %>
  </div>
</header>